name: ci-cd

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # 2. JDK 21 세팅
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      # 3. Spring Boot 빌드
      - name: Build (bootJar)
        run: |
          chmod +x gradlew
          ./gradlew clean bootJar

      - name: Restore application yaml files
        run: |
          base64 --decode <<< "${{ secrets.APPLICATION_YAML }}" > application.yaml
          base64 --decode <<< "${{ secrets.APPLICATION_COMMON_YAML }}" > application-common.yaml
          base64 --decode <<< "${{ secrets.APPLICATION_NOTE_YAML }}" > application-note.yaml
          base64 --decode <<< "${{ secrets.APPLICATION_GATEWAY_YAML }}" > application-gateway.yaml
          base64 --decode <<< "${{ secrets.APPLICATION_PLATFORM_YAML }}" > application-platform.yaml

      # 4. DockerHub 로그인
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5. Docker 이미지 빌드 & 푸시
      - name: Build & Push Docker Image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/note-vault
          TAG=latest

          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG

      # 6. Web EC2(Bastion) 통해 WAS 배포
      - name: Deploy via Web EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.WEB_HOST }}          # Public IP / Elastic IP
          username: ec2-user
          key: ${{ secrets.WEB_SSH_KEY }}        # Web EC2 접속용 pem
          script: |
            chmod +x /home/ec2-user/deploy/deploy-was.sh
            /home/ec2-user/deploy/deploy-was.sh
