name: ci-cd

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"


      - name: Build (bootJar)
        shell: bash
        run: |
          set -euo pipefail
          chmod +x gradlew
          ./gradlew clean bootJar


      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build & Push Docker Image
        shell: bash
        run: |
          set -euo pipefail

          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/note-vault
          TAG=latest

          docker build --no-cache -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG


      - name: Deploy via Web EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.WEB_HOST }}
          username: ec2-user
          key: ${{ secrets.WEB_SSH_KEY }}
          script: |
            set -e
            /home/ec2-user/deploy/deploy-was.sh
      
      
